"""Add category column to Habit model (Fix for NotNullViolation)

Revision ID: 0d10cef9f693
Revises: None
Create Date: 2025-11-23

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.sql import table, column

# revision identifiers, used by Alembic.
revision = '0d10cef9f693'
down_revision = None
branch_labels = None
depends_on = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # STEP 1: Add the column, but allow NULLs initially (temp: nullable=True)
    op.add_column('habit', sa.Column('category', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    
    # STEP 2: Populate existing rows with a non-null default value ('General')
    # This prevents the NotNullViolation error.
    
    # 2a. Define a temporary representation of the 'habit' table
    habit_table = table(
        'habit',
        column('category', sa.String)
    )
    
    # 2b. Run the update command
    op.execute(
        habit_table.update().where(habit_table.c.category == None).values(category='General')
    )
    
    # STEP 3: Alter the column to enforce NOT NULL moving forward
    # This matches your SQLModel definition where category is mandatory.
    op.alter_column('habit', 'category', nullable=False)
    
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('habit', 'category')
    # ### end Alembic commands ###